version: "3.8"

name: lock-stock-web

services:
  nuxt:
    container_name: lock-stock-nuxt
    build:
      context: ../app
      dockerfile: ../docker/images/node/Dockerfile
    volumes:
      - ../app:/app
    ports:
      - "3000:3000"
    tty: true
