name: lock-stock-web

version: "3.4"
services:
  lock-stock-web:
    container_name: lock-stock-web
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 8000
    volumes:
      - ../app/:/var/www/html/app
    tty: true