name: lock-stock-web

version: "3.4"

services:
  lock-stock-web:
    container_name: lock-stock-web
    image: node:lts
    working_dir: /var/www/html/app
    volumes:
      - ../app/:/var/www/html/app
    ports:
      - "5173:5173"
    command: npm run dev

